name: Codecov Action
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt install -y catch make gcc
      - name: "run tests"
        run: make test
      - name: "get code coverage"
        run: ./get-code-cov.sh
      - name: "upload code coverage"
        run: bash <(curl -s https://codecov.io/bash)
