name: Codecov Action

on:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install -y catch make gcc
      - name: Run tests
        run: make test
      - name: Get code coverage
        run: ./get-code-cov.sh
      - name: Upload code coverage
        run: bash <(curl -s https://codecov.io/bash)
